services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: "devops"
      MYSQL_ROOT_PASSWORD: "chiku"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - two-tier

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pchiku"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s   

  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "6060:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: chiku
      MYSQL_DB: devops
    networks:
      - two-tier    
    volumes:
      - mysql-data:/var/lib/mysql
    depends_on:
      - mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s    

volumes:
  mysql-data:

networks:
  two-tier:

